-- Create RxNorm tables in a SQLite database.
-- Adapted from their scripts/mysql/Table_scripts_mysql_rxn.sql

DROP INDEX IF EXISTS IDX_RXNCONSO_RXCUI;
CREATE INDEX IDX_RXNCONSO_RXCUI ON RXNCONSO(RXCUI);

DROP INDEX IF EXISTS IDX_RXNCONSO_RXAUI;
CREATE INDEX IDX_RXNCONSO_RXAUI ON RXNCONSO(RXAUI);

DROP INDEX IF EXISTS IDX_RXNCONSO_SAB;
CREATE INDEX IDX_RXNCONSO_SAB ON RXNCONSO(SAB);

DROP INDEX IF EXISTS IDX_RXNSAT_RXCUI;
CREATE INDEX IDX_RXNSAT_RXCUI ON RXNSAT(RXCUI);

DROP INDEX IF EXISTS IDX_RXNSAT_SAB;
CREATE INDEX IDX_RXNSAT_SAB ON RXNSAT(SAB);

DROP INDEX IF EXISTS IDX_RXNREL_RXCUI1;
CREATE INDEX IDX_RXNREL_RXCUI1 ON RXNREL(RXCUI1);

DROP INDEX IF EXISTS IDX_RXNREL_RXCUI2;
CREATE INDEX IDX_RXNREL_RXCUI2 ON RXNREL(RXCUI2);

DROP INDEX IF EXISTS IDX_RXNREL_RXAUI1;
CREATE INDEX IDX_RXNREL_RXAUI1 ON RXNREL(RXAUI1);

DROP INDEX IF EXISTS IDX_RXNREL_RXAUI2;
CREATE INDEX IDX_RXNREL_RXAUI2 ON RXNREL(RXAUI2);

DROP INDEX IF EXISTS IDX_RXNREL_RELA;
CREATE INDEX IDX_RXNREL_RELA ON RXNREL(RELA);
